### ISSUE TITLE
Sample did not work for me

### ISSUE THREAD

**Issue by FrunkDucker** [VytenisJ/log4net.Azure.Storage#3]
When using this, the log file name was literally log_{yyyyMMdd}.log (without the date inserted)

`<FileName type="log4net.Util.PatternString" value="log_{yyyyMMdd}.log" />`

I think this should be something like

`<FileName type="log4net.Util.PatternString" value="log_%date{yyyy-MM-dd}.log" />`

?

**Comment by VytenisJ** [comment]
Hi, @FrunkDucker ,

you are completely correct. I updated the documentation.

Thanks,
V
